name: nfc_attendance
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.17.0 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.1.0
  intl: ^0.19.0


dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
    
  fonts: 
    - family: ABeeZee
      fonts: 
        - asset: assets/fonts/ABeeZeeItalic.ttf
          weight: 400
        - asset: assets/fonts/ABeeZeeRegular.ttf
          weight: 400
    - family: Almarai
      fonts: 
        - asset: assets/fonts/AlmaraiBold.ttf
          weight: 700
